### ISSUE TITLE
Unable to download files due to Git LFS quota exceeded

### ISSUE THREAD

**Issue by Fuyujia799** [zhukun1020/HiCaD#3]
When cloning the repository, I encountered an error indicating that the Git LFS quota has been exceeded:

`Cloning into 'HiCaD'...
Downloading data/all_domain_data.tgz (256 MB)
Error downloading object: data/all_domain_data.tgz (ca1a3bc): Smudge error: Error downloading data/all_domain_data.tgz (ca1a3bcfe39e6ee9fa65ab7721c68c4c58de7146a081ed964ea6b82aec12c7ec): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.`

Could you please increase the Git LFS storage or provide an alternative method to access the large files?

Thank you!

**Comment by TechnicolorGUO** [comment]
same issue here

**Comment by zhukun1020** [comment]
https://drive.google.com/drive/folders/1HJU3YfJPh3_xTYj-2yQiWuIqhzfJ0Ls-?usp=sharing

**Comment by TechnicolorGUO** [comment]
Appreciate it with thanks!!

**Comment by Fuyujia799** [comment]
Thank you！！I can  now smoothly download the dataset.
